apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: testrepo-otel
build:
  artifacts:
    - image: index.docker.io/seankhliao/testrepo-otel
      docker:
        dockerfile: Dockerfile
  local:
    useBuildkit: true
deploy:
  kustomize:
    paths:
      - .
  kubeContext: kind-testrepo-otel
