apiVersion: v1
kind: Namespace
metadata:
  name: otel
---
apiVersion: v1
kind: Namespace
metadata:
  name: jaeger
---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana
---
apiVersion: v1
kind: Namespace
metadata:
  name: promtail
---
apiVersion: v1
kind: Namespace
metadata:
  name: loki
